/// Flutter icons Home
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Home
///      fonts:
///       - asset: fonts/Home.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class BottomIconData {
  BottomIconData._();

  static const _kFontFam = 'BottomIconData';
  static const String? _kFontPkg = null;

  static const IconData iconData_newsRoom = IconData(0xf39d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconData_newsRoom_reload = IconData(0xf332, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconData_test = IconData(0xf376, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconData_voca = IconData(0xf314, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconData_chat = IconData(0xf3c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData git_commit = IconData(0xf315, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconData_seeMore = IconData(0xf354, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData home = IconData(0xf35f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  // static const IconData grabber = IconData(0xf3ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
